[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "mysql", "nodejs_20"]

[phases.build]
cmds = ["composer install --no-interaction --prefer-dist --optimize-autoloader"]

[start]
cmd = "bash start.sh"
