name: Build Angular Frontend

on:
  push:
    paths:
      - 'cake-client/**'
  pull_request:
    paths:
      - 'cake-client/**'

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: cake-client

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: npm run build
