name: Laravel CI

on:
  push:
    paths:
      - '**.php'
      - 'composer.json'
      - 'artisan'
  pull_request:
  workflow_dispatch:


jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testing
        ports:
          - 3306:3306

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, mysql

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Create .env file
        run: cp .env.example .env

      - name: Generate APP_KEY
        run: php artisan key:generate

      - name: Run tests
        env:
          DB_CONNECTION: mysql
          DB_DATABASE: testing
          DB_USERNAME: root
          DB_PASSWORD: root
        run: php artisan test
